### ISSUE TITLE
건의: E-on 홈페이지

### ISSUE THREAD

**Issue by GKO95** [fora22/CreateBlog#12]
[E-on 홈페이지](../#e-on-homepage)를 만들고 싶어 하는데, 그러면 [E-on GitHub Pages](https://github.com/Electronic-over-Network/Electronic-over-Network.github.io)를 활용하는건 어떤지 건의합니다. 아직까지 활용도가 적은 E-oN 조직 계정을 이렇게라도 활용하는 게 좋지 않을까 생각합니다.

해당 GitHub Pages는 다음과 같은 설정이 이미 마련된 상태입니다.
* Jekyll 번들 설정
* kramdown w/ rouge 구문 하이라이트
* jQuery (자바스크립트 라이브러리)
* MathJax (LaTeX 입력)
* `_include`, `_layout`, `assets` 등 Jekyll 디자인에 필요한 폴더

기본적으로 minima 테마를 불러왔지만, 이를 번들에서 삭제시키고 직접 자체제작을 하므로써 여러분이 원하시는 HTML & CSS, 그리고 자바스크립트 연습을 할 수 있습니다. 해당 내용에 관심이 있으시면 Jekyll 사이트에 대한 간략한 내용을 여기서 참고하실 수 있습니다.

* [*GitHub Pages에서 Jekyll 생성하기*](https://gko95.github.io/blog/ko.creating-jekyll-site/)
* [*GitHub Pages에서 Jekyll 설정하기*](https://gko95.github.io/blog/ko.configuring-jekyll-site/)
* [*GitHub Pages에서 Jekyll 디자인하기*](https://gko95.github.io/blog/ko.designing-jekyll-site/)

**Comment by fora22** [comment]
좋은 의견 감사합니다. 이전에 한번 @JSY8869  와 이야기 나눴습니다(Jekyll 혹은 Gatsby 와 같은 정적 생성 사이트를 배포하는 방식과 직접 Homepage를 만드는 방법 중 어떤 것을 택할거냐에 대한 논의). 

이야기 결과, WEB에 대한 공부도 겸하는 것이므로 직접 한 번 만드는 것으로 진행해보자는 것이 결론이었습니다.

- 개인적으로 저는 Jekyll 로 만드는 홈페이지도 언젠가 해 볼 예정이었습니다.
- Gatsby로도 홈페이지를 만들어 볼 예정이었구요.
- 현재는 React로 만들고 있지만 나중에(2022년 정도)는 vue.js로도 할 예정입니다.
- 다 해볼려면 오래 걸릴 듯.

# 하지만 [건의: E-on 홈페이지](https://github.com/fora22/CreateBlog/issues/12#issue-779767177)를 듣고 보니

지금 React로 진행하고 있는 Page의 문제점은 프로젝트 완성이 1년 정도 걸릴 것이라는 점 입니다. 이는 현재 EoN 회장이 @JSY8869  이고 이 임기가 다 끝나는 2021년 겨울(혹은 더 늦으면 2022년 초)에 완성된다는 뜻 입니다. 따라서 다음과 같이 제안하고 싶습니다.

# 제안 내용
## 1. Jekyll로 홈페이지 만들어서 17기 신청을 거기서 받는다. @JSY8869 
2021년 신입 기수를 모집하는 2월 말 에서 3월 초 전까지 Jekyll 혹은 Gatsby를 활용한(Github pages를 생각하면 Jekyll이 좋아 보임) **홍보용 홈페이지를 만든다.** 이후 *React를 활용한 홈페이지는 홍보 홈페이지가 구축되면 다시 실행한다.* 홈페이지의 기능은 다음과 같다.
   - E-on 동아리 소개
   - E-on 동아리 활동(공모전 입상 및 프로젝트 활동) 정리
   - E-on 동아리 17기 신청 홈페이지

## 2. 새로운 Collaborator @GKO95 
괜찮다면 @GKO95  님이 홍보용 홈페이지 만드는 것을 도와주시고 이후 React 프로젝트를 같이 하면 어떨까요?

## 3. [FlowDebugger](https://github.com/GKO95/UWP.FlowDebugger/tree/master) @GKO95 

흔쾌히 하자 해놓고 이렇게 말해서 죄송하지만 FlowDebugger는 중단하는 것이 어떨까요? UWP가 생각보다 재미가 없었고, 서로 마지막 커밋이 2개월 전이면 중단하는 것이 나아 보입니다...ㅎ

**Comment by GKO95** [comment]
제안 내용에 대한 답변입니다.

## 2. 새로운 Collaborator
네, Jekyll 사이트 제작에 도와드릴 수 있습니다. 하지만 React가 자바스크립트 라이브러리인 점만 알고 있으며, 이에 대한 진행사항이나 정확히 무엇을 개발하려는 것인지 등의 자세한 내용은 아직 모르고 있습니다. 그리고 "1년 정도 걸릴 것"에 대하여 설명해 주셨으면 합니다.

## 3. [FlowDebugger](https://github.com/GKO95/UWP.FlowDebugger) 프로젝트
해당 프로젝트에 대한 기여도는 현저히 낮습니다. 더더욱 중요한 것은 프로젝트 책임자인 제가 다른 작업에 몰두하고 있어 우선순위 외에 있습니다. 작업 진척이 전혀 없기 때문에 프로젝트를 중단하고 리포지터리를 이 시각부로 <span style="color: red;">24시간 이내 삭제</span>하겠습니다.

**Comment by fora22** [comment]
> ## 2. 새로운 Collaborator
> 이에 대한 진행사항이나 정확히 무엇을 개발하려는 것인지 등의 자세한 내용은 아직 모르고 있습니다. 그리고 "1년 정도 걸릴 것"에 대하여 설명해 주셨으면 합니다.

1년 정도 걸릴 것이라는 이야기는 이 프로젝트가 여가 시간(?)에 진행하는 프로젝트이기 때문입니다. 정확히 무엇을 개발하려는 지는 EoN 홈페이지인데 텍스트로 설명드리기는 한계가 있을 것 같습니다. 

2021년 01월 14일 저녁 11시에 Google meet을 통한 회의가 있을 예정인데 참여하셔서 설명을 듣는건 어떠하신가요? @GKO95

**Comment by GKO95** [comment]
네, 회의 참여하겠습니다.

**Comment by fora22** [comment]
> 네, 회의 참여하겠습니다.

회의에 참여할 이메일 주소 알려주세요~

**Comment by GKO95** [comment]
구글 계정이라면 Gihwan.Ko@gmail.com 입니다.
