### ISSUE TITLE
레포지터리에 대하여 건의사항입니다!

### ISSUE THREAD

**Issue by JSY8869** [fora22/CreateBlog#4]
## 레포지터리
- CreateBlog에서 개인 블로그를 만들고 EonBlog 같은 레포지터리를 새로 만드는 게 어떨까요? 비슷한 활동이지만 내용이 좀 다르다고 생각이 들어서 건의드립니닷!
## plan
- plan의 경우 책이 오늘 늦게 온다고 해서 내일 바로 올리겠습니다ㅠㅠ

**Comment by fora22** [comment]
음 내 생각은 반대인게 그럼 Issue 관리나 회의 내용 같은게 옮겨 가지 않으니까 EonBlog를 포함한 Blog 만드는 건 여기서 연습하고 개인 Blog는 각자 알아서 새로운 레포지토리 파는게 나을거같다는 생각이 드네
- CreateBlog가 맘에 안들면 이름 변경 가능함(레포지토리 이름 변경)
- 이 레포지토리는 개인적으로 Blog를 만드는 법에 대해 공부하는 레포지토리가 되었으면 좋겠어서 EonBlog용 레포지토리가 아니였음 좋겠음(포괄하는 개념의 이름이었으면 좋겠음)

**Comment by JSY8869** [comment]
아아 개인 Blog랑 구분만 된다면 상관은 없을 것 같아요! 이대로 진행하겠슴다!
